stages:          # List of stages for jobs, and their order of execution
  - package
  - test
  - docker
  - deploy
.maven :
    image : maven:3.6.3-jdk-11
    cache:
      key: maven
      paths:
          - .m2
      policy: pull-push
    variables: 
        MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Djansi.force=true"
        MAVEN_CLI_OPTS: "--settings maven.settings.xml --errors --show-version -Dstyle.color=always"
    
maven-package:
    stage : package
    extends : .maven
    script:
        - mvn package -DskipTests -Ddocker.skip=true
        #- rm -rf target/*
    artifacts:
      paths:
        - target/
      untracked: false
      expire_in: 30 days

maven_verify:
    stage: test
    extends: .maven
    dependencies: [maven-package]
    script:
        - mvn clean install -DskipTests -Ddocker.skip=true
        - mvn verify -DskipTests -Dmaven.main.skip -Ddocker.skip=true

docker-image:
    stage: docker
    dependencies: [maven-package]
    before_script:
        - curl --show-error --silent --location --output "/usr/local/bin/img" "https://github.com/genuinetools/img/releases/download/v0.5.11/img-linux-amd64" && chmod a+x "/usr/local/bin/img" && img --version
    script:
    - img build --no-cache -f common/gke.Dockerfile --build-arg JVM_PARAMS=$JVM_PARAMS -t $GCR_IMAGE:$UNIQUE_VERSION target/gesClinic
    - img push "$GCR_IMAGE:$UNIQUE_VERSION"

