server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password:
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    dispatch-options-request: true

bezkoder.app.jwtSecret: N2U3YThkNWIzYzYzNDI5ODlhMWU4MDczZTMxNmM2ODUyNzNjZmI3ZjQzMjkyNGQyOTI0NGJjOGMwM2U5YTFkODlhODRjMjhjMTYxNzI1YjNlMjQzYjIxOTBmZmYzNjkzMGZiMTQzMmU0NjIzM2ZiMWY1MDQzMThlYjYxOThlZGU=
bezkoder.app.jwtExpirationMs: 86400000
bezkoder:
  app:
    jwtCookieName: security
