server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://82.165.113.198:5432/clinic_v2
    #username: postgres
    username: mendel
    password: clinic123
  jpa:
    hibernate:
      ddl-auto: update
      reload: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
  mvc:
    dispatch-options-request: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

bezkoder.app.jwtSecret: bezKoderSecretKey
bezkoder.app.jwtExpirationMs: 86400000